os: linux
dist: xenial
language: go

services:
  - docker

jobs:
  fast_finish: true
  include:
    - name: MySQL8.0-1.17.x
      go: 1.17.x
      env:
        - XUN_UNIT_NAME=mysql  XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql8.0.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3308)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql8.0 # Start MySQL 8.0 service
    - name: MySQL8.0-1.15.x
      go: 1.15.x
      env:
        - XUN_UNIT_NAME=mysql  XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql8.0.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3308)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql8.0 # Start MySQL 8.0 service
    - name: MySQL5.7-1.17.x
      go: 1.17.x
      env:
        - XUN_UNIT_NAME=mysql  XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql5.7.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3306)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql5.7 # Start MySQL 5.7 service
    - name: MySQL5.7-1.15.x
      go: 1.15.x
      env:
        - XUN_UNIT_NAME=mysql  XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql5.7.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3306)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql5.7 # Start MySQL 5.7 service
    - name: MySQL5.6-1.17.x
      go: 1.17.x
      env:
        - XUN_UNIT_NAME=mysql5.6 XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql5.6.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3307)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql5.6 # Start MySQL 5.6 service
    - name: MySQL5.6-1.15.x
      go: 1.15.x
      env:
        - XUN_UNIT_NAME=mysql5.6 XUN_UNIT_DRIVER=mysql XUN_UNIT_DRIVER=mysql XUN_UNIT_LOG=$HOME/mysql5.6.log XUN_UNIT_SOURCE="root:123456@tcp(127.0.0.1:3307)/xun?charset=utf8mb4&parseTime=True&loc=Local" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh mysql5.6 # Start MySQL 5.6 service
    - name: Postgres9.6-1.17.x
      go: 1.17.x
      env:
        - XUN_UNIT_NAME=postgres XUN_UNIT_DRIVER=postgres XUN_UNIT_LOG=$HOME/postgres.7.log XUN_UNIT_SOURCE="postgres://postgres:123456@127.0.0.1/xun?sslmode=disable" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh postgres9.6 # Start PostgresSQL 9.6 service
    - name: Postgres9.6-1.15.x
      go: 1.15.x
      env:
        - XUN_UNIT_NAME=postgres XUN_UNIT_DRIVER=postgres XUN_UNIT_LOG=$HOME/postgres.7.log XUN_UNIT_SOURCE="postgres://postgres:123456@127.0.0.1/xun?sslmode=disable" GO111MODULE=on XUN_MODE=test
      before_install:
        - unit/service.sh postgres9.6 # Start PostgresSQL 9.6 service
    - name: SQLite3-1.17.x
      go: 1.17.x
      env:
        - XUN_UNIT_NAME=sqlite3 XUN_UNIT_DRIVER=sqlite3  XUN_UNIT_LOG=$HOME/sqlite3.log XUN_UNIT_SOURCE="unit-test.db" GO111MODULE=on XUN_MODE=test
    - name: SQLite3-1.15.x
      go: 1.15.x
      env:
        - XUN_UNIT_NAME=sqlite3 XUN_UNIT_DRIVER=sqlite3  XUN_UNIT_LOG=$HOME/sqlite3.log XUN_UNIT_SOURCE="unit-test.db" GO111MODULE=on XUN_MODE=test
git:
  depth: 10
install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

go_import_path: github.com/yaoapp/xun

script:
  - export
  - make vet
  - make fmt-check
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
