os: linux
dist: xenial
language: go

services:
  - docker

jobs:
  fast_finish: true
  include:
    - go: 1.15.x
      env:
        - GO111MODULE=on
git:
  depth: 10
before_install:
  # Create MySQL-5.7 service
  - docker pull mysql:5.7.25
  - docker run --name=mysql5.7 -d -p 3308:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:5.7.25
  - docker exec mysql5.7 mysql -uroot -p123456 -e "CREATE DATABASE xun CHARACTER SET utf8 COLLATE utf8_general_ci"
  - docker exec mysql5.7 mysql -uroot -p123456 -e "CREATE USER xun@'%' IDENTIFIED BY '123456'"
  - docker exec mysql5.7 mysql -uroot -p123456 -e "GRANT SELECT ON xun.* TO 'xun'@'%'";
install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

go_import_path: github.com/yaoapp/xun

script:
  - make vet
  - make fmt-check
  - make misspell-check
  - docker exec mysql5.7 mysql -uroot -p123456 -e "SHOW DATABASES"

after_success:
  - bash <(curl -s https://codecov.io/bash)
