export XUN_UNIT_LOG="/Users/max/Code/yao/xun/unit/sqlite.log"
export XUN_UNIT_SQLITE3_DSN="file:///Users/max/Code/yao/xun/unit/sqlite-unittest.db"
# export XUN_UNIT_SQLITE3_DSN=":memory:"
export XUN_UNIT_DSN="sqlite3"
export XUN_MODE="test"