export XUN_UNIT_NAME="sqlite3"
export XUN_UNIT_LOG="/Users/max/Code/yao/xun/unit/sqlite.log"
export XUN_UNIT_SOURCE="file:///Users/max/Code/yao/xun/unit/sqlite-unittest.db"
# export XUN_UNIT_SQLITE3_DSN=":memory:"
export XUN_UNIT_DRIVER="sqlite3"
export XUN_MODE="test"